version: '3.8'
services:
  nextjs_template:
    build:
      dockerfile: "dockerfiles/Dockerfile"
      context: ./
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3003:3003
